# Generated by Django 3.0.8 on 2020-11-10 20:39

from django.db import migrations, models
import project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=project.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
