# Generated by Django 3.0.8 on 2020-11-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pet',
        ),
    ]
