"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .config.general import *
from .config.apps import *
from .config.rest_framework import *
from .config.databases import *
from .config.staticfiles import *
from .config.security import *
